### ISSUE TITLE
data-key confusion

### ISSUE THREAD

**Issue by devmondo** [DylanPiercey/set-dom#10]
hi again,

i have this original html

```
<div id="mount" class="test">
    normal text
    <h1 data-key="ignore">first render</h1>
    <h1 data-key="ignore1">first render duplicate</h1>
</div>
```

to diff with 

```
<div id="mount" class="test">
    <h1 data-key="ignore">second render</h1>
    <h1 data-key="ignore1">second render duplicate</h1>
    normal text
</div>
```

i thought that one of the goals of `data-key` is to ignore diffing its element. but with the above the inner text for `H1` is still changing. 

maybe i am doing it totally wrong, this is important as sometimes you really want to avoid diffing an element, for example you have a child component with its own view model behind so if we cant ignore this element, this means we will rerun the component function each time we diff.

i fully understand the solution suggested here #8  but the point is that i dont want to rerun the child component function every time, i want it to handle its own diffing decision.

i think in virtual dom world it is called `thunk`. 

sorry if i dont make sense and thanks in advanced.

**Comment by DylanPiercey** [comment]
`data-key` does not ignore an element for diffing, instead it helps the diffing algorithm figure out how things have moved.

Say for example you have three profiles with a delete button:

```js
html`
<div data-key="profile-1">
    <div class="name">Billy</div>
    <div class="age">10</div>
    <a href="/delete-user/1">Delete Profile</a>
</div>

<div data-key="profile-2">
    <div class="name">Sally</div>
    <div class="age">11</div>
    <a href="/delete-user/2">Delete Profile</a>
</div>

<div data-key="profile-3">
    <div class="name">John</div>
    <div class="age">12</div>
    <a href="/delete-user/3">Delete Profile</a>
</div>
`
```

Now say we delete the user in the middle and run a diff.
What would happen without keys is that the first two divs would be updated, and the last one would be removed (because it has no idea that things have shifted around, just that things are different now).

If we use data-keys (which the example was using) we now have an identifier for elements that have meaning so we can know when they are moved around vs being removed vs being updated. This means that if we do the same diff (remove the user from the middle) with an algorithm that can take into account where things are (data-key) then all we have to do is remove the middle div which is much less work.

---

Thats how `data-key` works, which is more/less the same as it does in react. What you seem to be looking for is a way to say "DO NOT DIFF THIS ELEMENT NO MATTER WHAT", which would actually be quite useful for things like google maps, or other embeds.

I am thinking of adding another `data` identifier to help the algorithm that would solve this problem but the name could use some [bikeshedding](https://en.wiktionary.org/wiki/bikeshedding), i'm thinking `data-ignore`.

What are your thoughts?

**Comment by devmondo** [comment]
man i am always amazed by your quick and elaborate response.

i fully understand what you explained and it was one of the first things i checked before using your awesome lib, because as you said it is really important.

as a quick embarrassing hack i replaced this line here [set-dom](https://github.com/DylanPiercey/set-dom/blob/master/lib/index.js#L145)

with this and it worked perfectly!

```
  if (a.nodeType === Node.ELEMENT_NODE) {
                if (!a.hasAttribute(`diff-ignore`) ) setNode(a, b);
            }
            else {
                setNode(a, b);
            }
```

**Comment by DylanPiercey** [comment]
That's more/less what I would do. I think i'm just going to go with `data-ignore` (can't use `diff-ignore` for browser compatibility).

**Comment by devmondo** [comment]
hahahha, i am glad you agree :)

i think the `data-key` and `data-ignore` should be configurable by options, cause you never know what conflict you might get with other projects, but `data-ignore` is fine.

**Comment by DylanPiercey** [comment]
Just release 2.0.0 which now has `data-ignore` and the ability to change the attribute used for both `data-ignore` and `data-key`.

**Comment by devmondo** [comment]
wow you are fast!

thanks mate for the update :)

**Comment by DylanPiercey** [comment]
No problem, hope it suites your needs.
